[package]
name = "fog-pack"
version = "0.1.0"
authors = ["Scott Teal"]
readme = "README.md"
keywords = [ "fog-pack", "validator", "serialization", "deserialization" ]
categories = [ "encoding" ]
repository = "https://github.com/Cognoscan/fog-pack"
homepage = "https://github.com/Cognoscan/fog-pack"
documentation = "https://docs.rs/fog-pack"
license = "MIT OR Apache-2.0"
description = "Binary Data format supporting immutable references, schema, and compression"
exclude = [ "media/*", "misc_docs/*" ]

[dependencies]
libc = "0.2"
constant_time_eq = "0.1.3"
blake2-rfc = "0.2.18"
libsodium-sys = "0.2.2"
byteorder = "1"
num-traits = "0.2"
regex = "1"
ieee754 = "0.2.6"
zstd-safe = "2.0"
bytecount = "0.6.0"
unicode-normalization = "0.1.12"

[dev-dependencies]
tempfile = "3.0.8"
rand = "0.6.5"
colored = "1.7"
hex = "0.3.2"
serde_json = "1.0"
